import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'bbanyai' at '12/29/16 10:32 PM' with Gradle 2.12
 *
 * @author bbanyai, @date 12/29/16 10:32 PM
 */
public class ImageAsserterTest {
    @Test public void testSomeLibraryMethod() {
        ImageAsserter classUnderTest = new ImageAsserter();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.assertSimilarity());
    }
}
